"""update models

Revision ID: 3ec67724afb2
Revises: 48a21d17dc36
Create Date: 2025-09-12 11:52:18.815213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec67724afb2'
down_revision: Union[str, None] = '48a21d17dc36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('returns', sa.Column('inventory_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('returns', 'inventory_id')
    # ### end Alembic commands ###
