"""update models

Revision ID: 48a21d17dc36
Revises: b5a9450de9b1
Create Date: 2025-09-12 11:38:17.968999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a21d17dc36'
down_revision: Union[str, None] = 'b5a9450de9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('returns', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('returns', sa.Column('quantity', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
