"""update models

Revision ID: 715900ce77f9
Revises: 3ec67724afb2
Create Date: 2025-09-12 12:01:38.188243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715900ce77f9'
down_revision: Union[str, None] = '3ec67724afb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('returns', sa.Column('inventory_id', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('returns', 'inventory_id')
    # ### end Alembic commands ###
